/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/About/': RouteRecordInfo<'/About/', '/About', Record<never, never>, Record<never, never>>,
    '/Artist/': RouteRecordInfo<'/Artist/', '/Artist', Record<never, never>, Record<never, never>>,
    '/Demo/': RouteRecordInfo<'/Demo/', '/Demo', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Home/': RouteRecordInfo<'/Home/', '/Home', Record<never, never>, Record<never, never>>,
    '/Mumber/': RouteRecordInfo<'/Mumber/', '/Mumber', Record<never, never>, Record<never, never>>,
    '/Music/': RouteRecordInfo<'/Music/', '/Music', Record<never, never>, Record<never, never>>,
    '/Radio/': RouteRecordInfo<'/Radio/', '/Radio', Record<never, never>, Record<never, never>>,
  }
}
